### ISSUE TITLE
Does not work with EXTRAVERSION

### ISSUE THREAD

**Issue by onkobu** [cateee/lkddb#1]
```
Traceback (most recent call last):
  File "./build-lkddb.py", line 77, in <module>
    make(args, kerneldir, dirs)
  File "./build-lkddb.py", line 19, in make
    tree = lkddb.linux.LinuxKernelTree(lkddb.TASK_BUILD, kerneldir, dirs)
  File "/home/onkobu/git/lkddb/lkddb/linux/__init__.py", line 106, in __init__
    self.retrieve_version()
  File "/home/onkobu/git/lkddb/lkddb/linux/__init__.py", line 161, in retrieve_version
    assert False, "Unknown structure of EXTRAVERSION (%s) in kernel version" % extra
AssertionError: Unknown structure of EXTRAVERSION (-gentoo) in kernel version
```

I'd give it a try to form the foundation for a kernel config recommendation tool like the security ones. Instead of rendering a complete config it'd outline deviations from optimum, e.g. drivers not necessary because the hardware doesn't exist on the current system. (Along the lines of improving your autoconfig thingy.)

**Comment by cateee** [comment]
Hello,

On 02.04.21 09:33, Onkobu Tanaake wrote:
> |Traceback (most recent call last): File "./build-lkddb.py", line 77, in 
> <module> make(args, kerneldir, dirs) File "./build-lkddb.py", line 19, 
> in make tree = lkddb.linux.LinuxKernelTree(lkddb.TASK_BUILD, kerneldir, 
> dirs) File "/home/onkobu/git/lkddb/lkddb/linux/__init__.py", line 106, 
> in __init__ self.retrieve_version() File 
> "/home/onkobu/git/lkddb/lkddb/linux/__init__.py", line 161, in 
> retrieve_version assert False, "Unknown structure of EXTRAVERSION (%s) 
> in kernel version" % extra AssertionError: Unknown structure of 
> EXTRAVERSION (-gentoo) in kernel version |
> 
> I'd give it a try to form the foundation for a kernel config 
> recommendation tool like the security ones. Instead of rendering a 
> complete config it'd outline deviations from optimum, e.g. drivers not 
> necessary because the hardware doesn't exist on the current system. 
> (Along the lines of improving your autoconfig thingy.)

you can replace the line with assertion:
    assert False, "Unknown structure of EXTRAVERSION (%s) in kernel 
version" % extra

to
    version_dict['numeric2'] = 0

I put the assertion so that I'll notice quickly when upstream will 
update the semantic (in past it was "pre", "-pre", "-rc", for beta 
versions), but I think I can just put a warning, and allow distribution 
string.

I should check if I miss some other cases.

giacomo

**Comment by onkobu** [comment]
This is specific to Gentoo and I assume it is the line `# Linux/x86 5.4.80-gentoo-r1 Kernel Configuration`. I'm not so into Python but you have my deepest respect for a language that sophisticated. (=no PR from my side since I'm certain to shoot myself **and** others in the foot with Python.)

Do you need more lines/ samples for other possible (Gentoo-) quirks? Tools like https://github.com/slimm609/checksec.sh (checksec.sh -kernel) or https://github.com/a13xp0p0v/kconfig-hardened-check work right away.
